/**
 * README Generator
 *
 * Generates markdown documentation from operation schema
 */

import { OperationSchema } from '../types';
import {
  generateConnectorId,
  generateWebhookUrl
} from '../utils/naming';

/**
 * Generate README markdown from operation schema
 */
export function generateReadme(schema: OperationSchema): string {
  const connectorId = generateConnectorId(schema.nodeId, schema.resource, schema.operation);
  const webhookUrl = generateWebhookUrl(connectorId);

  // Generate input parameters table
  const inputParamsTable = schema.parameters.map(param => {
    const required = param.required ? 'Yes' : 'No';
    const description = param.description || '';
    return `| \`${param.name}\` | ${param.type} | ${required} | ${description} |`;
  }).join('\n');

  return `# Catalyst ${schema.displayName} Connector

${schema.description}

## Installation

### 1. Import n8n Workflow

1. Open your n8n instance
2. Click **Workflows** > **Import from File**
3. Select \`${connectorId}.n8n.json\`
4. **Configure credentials** for ${schema.nodeName} in n8n
5. **Activate** the workflow

Webhook URL: \`${webhookUrl}\`

### 2. Deploy Element Template

Copy \`${connectorId}.element.json\` to your Camunda Modeler templates directory.

## Input Parameters

| Variable | Type | Required | Description |
|----------|------|----------|-------------|
${inputParamsTable}

## Output Variables

| Variable | Type | Description |
|----------|------|-------------|
| \`success\` | Boolean | Whether the request succeeded |
| \`statusCode\` | Number | HTTP status code |
| \`responseBody\` | Object | Response data from ${schema.nodeName} API |
| \`error\` | String | Error message if failed |

## Usage Example

1. Deploy the example BPMN process (\`${connectorId}.bpmn\`)
2. Start a new process instance
3. Fill in the required input parameters in the user task
4. The service task will call ${schema.nodeName} via n8n

## Files

- \`${connectorId}.n8n.json\` - n8n webhook workflow
- \`${connectorId}.element.json\` - Camunda Modeler template
- \`${connectorId}.bpmn\` - Example BPMN process
- \`README.md\` - This documentation
- \`connector.json\` - Connector metadata

## Configuration

### n8n Credentials

This connector requires ${schema.nodeName} credentials to be configured in n8n:

${schema.credentials.map(cred => `- \`${cred}\``).join('\n')}

Configure credentials in n8n under **Settings** > **Credentials** > **Add Credential**.

### Webhook URL Allowlist

Ensure your Catalyst Bridge allows the webhook URL prefix:
\`\`\`
http://catalyst-n8n:5678/webhook/
\`\`\`

---

*Generated by Catalyst Connector Generator*
`;
}
